#!/bin/bash

#######################################################################
# 
# A simple script for 'deploying' static HTML sites to a webserver.
# rdeploy expects to read configuration options from a file (in
# the directory from which it's run) named '.rdeploy' and a list
# of files to ignore from a file called 'rdeploy-ignore.'
#
#######################################################################


# Configuration options
shopt -s extglob
configfile=".rdeploy"
ignorefile=".rdeploy-ignore"

###############################
# Read options from config file

while IFS='= ' read left right
do
    if [[ ! $left =~ ^\ *# && -n $left ]]; then
        right="${right%%\#*}"    # Del in line right comments
        right="${right%%*( )}"   # Del trailing spaces
        right="${right%\"*}"     # Del opening string quotes 
        right="${right#\"*}"     # Del closing string quotes 
        declare $left="$right"
    fi
done < $configfile


# Deploy!
command="rsync -avz --delete --exclude-from $ignorefile ./ $user@$host:$path"
$command
